global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gradio_app_metrics'
    static_configs:
      - targets: ['gradio_app:8000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['gradio_app:9100']